"""Stable records used by the 1,000-candidate collection lane."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import StrEnum
from typing import Any


class Phase(StrEnum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"


PHASE_TARGETS = {Phase.A: 50, Phase.B: 200, Phase.C: 500, Phase.D: 1000}


class SourceTier(StrEnum):
    TIER_1 = "tier_1"
    TIER_2 = "tier_2"
    TIER_3 = "tier_3"
    TIER_4 = "tier_4"


TRUST_GRADE_TO_TIER = {
    "A": SourceTier.TIER_1,
    "B": SourceTier.TIER_2,
    "C": SourceTier.TIER_3,
    "D": SourceTier.TIER_4,
}


class ReviewStatus(StrEnum):
    AUTO_REJECTED = "auto_rejected"
    AUTO_CANDIDATE = "auto_candidate"
    NEEDS_HUMAN_REVIEW = "needs_human_review"
    VERIFIED = "verified"
    ACCEPTED = "accepted"


class AcceptanceStatus(StrEnum):
    REJECTED = "rejected"
    PENDING = "pending"
    VERIFIED = "verified"
    ACCEPTED = "accepted"


class DuplicateStatus(StrEnum):
    UNIQUE = "unique"
    SUSPECTED = "suspected"
    CONFIRMED = "confirmed"


class TopicCategory(StrEnum):
    OPENING_TRADE = "OPENING_TRADE"
    PORT_MARITIME = "PORT_MARITIME"
    RAIL_TRANSPORT = "RAIL_TRANSPORT"
    URBAN_INFRASTRUCTURE = "URBAN_INFRASTRUCTURE"
    COLONIAL_CITY = "COLONIAL_CITY"
    ECONOMY_FINANCE = "ECONOMY_FINANCE"
    ARCHITECTURE_HERITAGE = "ARCHITECTURE_HERITAGE"
    EDUCATION_RELIGION = "EDUCATION_RELIGION"
    INDEPENDENCE_STUDENT_MOVEMENT = "INDEPENDENCE_STUDENT_MOVEMENT"
    LABOR_PEASANT_MOVEMENT = "LABOR_PEASANT_MOVEMENT"
    PERSON_HISTORY = "PERSON_HISTORY"
    POST_LIBERATION = "POST_LIBERATION"


class HardRejectionCode(StrEnum):
    NO_PROVENANCE = "NO_PROVENANCE"
    NO_PUBLISHER = "NO_PUBLISHER"
    NOT_MOKPO_RELEVANT = "NOT_MOKPO_RELEVANT"
    NO_HISTORICAL_BODY = "NO_HISTORICAL_BODY"
    TITLE_ONLY = "TITLE_ONLY"
    SEARCH_RESULT_ONLY = "SEARCH_RESULT_ONLY"
    SEO_AUTOGENERATED = "SEO_AUTOGENERATED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    CAPTCHA = "CAPTCHA"
    PAYWALL = "PAYWALL"
    ROBOTS_BLOCKED = "ROBOTS_BLOCKED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    RIGHTS_RESTRICTED = "RIGHTS_RESTRICTED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    OCR_CORRUPTION = "OCR_CORRUPTION"
    DUPLICATE_EXACT = "DUPLICATE_EXACT"
    DUPLICATE_MIRROR = "DUPLICATE_MIRROR"
    UNATTRIBUTED_CLAIMS = "UNATTRIBUTED_CLAIMS"
    TIER4_DISCOVERY_ONLY = "TIER4_DISCOVERY_ONLY"


@dataclass(slots=True)
class RightsEvidence:
    publisher: str = ""
    rights_holder: str = ""
    policy_url: str = ""
    document_rights_url: str = ""
    license_text: str = ""
    kogl_type: str = ""
    commercial_use: str = "unknown"
    modification: str = "unknown"
    redistribution: str = "unknown"
    third_party_material_warning: bool = False
    checked_at: str = ""
    human_review_required: bool = True


@dataclass(slots=True)
class CandidateDocument:
    candidate_id: str
    batch_id: str
    phase: Phase
    source_id: str
    source_url: str
    canonical_url: str
    source_title: str
    publisher: str
    institution: str
    publisher_family: str
    source_tier: SourceTier
    document_type: str
    topic_categories: list[TopicCategory]
    historical_period: str
    location: list[str]
    discovered_at: str
    fetched_at: str
    raw_path: str
    raw_sha256: str
    extracted_path: str
    extracted_sha256: str
    normalized_body_sha256: str
    response_final_url: str
    response_http_status: int
    response_content_type: str
    extraction_status: str
    extraction_method: str
    language: str
    robots_status: str
    access_status: str
    rights_status: str
    license: str
    kogl_type: str
    rights_evidence: RightsEvidence
    provenance: dict[str, Any]
    duplicate_status: DuplicateStatus = DuplicateStatus.UNIQUE
    duplicate_group: str = ""
    duplicate_of: str = ""
    duplicate_method: str = ""
    authority_score: int = 0
    provenance_score: int = 0
    historical_relevance_score: int = 0
    mokpo_relevance_score: int = 0
    corroboration_score: int = 0
    content_quality_score: int = 0
    objectivity_score: int = 0
    rights_score: int = 0
    uniqueness_score: int = 10
    total_quality_score: int = 0
    review_status: ReviewStatus = ReviewStatus.NEEDS_HUMAN_REVIEW
    acceptance_status: AcceptanceStatus = AcceptanceStatus.PENDING
    rejection_reasons: list[HardRejectionCode] = field(default_factory=list)
    fact_conflict: bool = False
    conflicting_values: list[dict[str, Any]] = field(default_factory=list)
    body_text: str = field(default="", repr=False)
    publication_metadata: dict[str, str] = field(default_factory=dict)
    document_id: str = ""

    def __post_init__(self) -> None:
        if not self.document_id:
            self.document_id = self.candidate_id
        elif self.document_id != self.candidate_id:
            raise ValueError("document_id must match candidate_id")

    @classmethod
    def from_dict(cls, value: dict[str, Any], *, body_text: str = "") -> "CandidateDocument":
        data = dict(value)
        data["phase"] = Phase(data["phase"])
        data["source_tier"] = SourceTier(data["source_tier"])
        data["topic_categories"] = [TopicCategory(item) for item in data["topic_categories"]]
        data["rights_evidence"] = RightsEvidence(**data["rights_evidence"])
        data["duplicate_status"] = DuplicateStatus(data["duplicate_status"])
        data["review_status"] = ReviewStatus(data["review_status"])
        data["acceptance_status"] = AcceptanceStatus(data["acceptance_status"])
        data["rejection_reasons"] = [HardRejectionCode(item) for item in data["rejection_reasons"]]
        data["body_text"] = body_text
        return cls(**data)

    def to_dict(self, *, include_body: bool = False) -> dict[str, Any]:
        value = asdict(self)
        if not include_body:
            value.pop("body_text", None)
        return value


@dataclass(slots=True)
class VerifiedDocument:
    candidate_id: str
    verified_document_id: str
    verified_at: str
    verified_by: str
    source_url: str
    canonical_url: str
    source_title: str
    publisher: str
    publisher_family: str
    source_tier: SourceTier
    topic_categories: list[TopicCategory]
    historical_period: str
    location: list[str]
    raw_path: str
    raw_sha256: str
    processed_path: str
    rights_status: str
    license: str
    kogl_type: str
    rights_evidence: RightsEvidence
    provenance: dict[str, Any]
    total_quality_score: int
    fact_conflict: bool
    conflicting_values: list[dict[str, Any]]
    review_status: ReviewStatus = ReviewStatus.ACCEPTED
    acceptance_status: AcceptanceStatus = AcceptanceStatus.ACCEPTED
    verification_notes: str = ""

    @classmethod
    def from_candidate(
        cls, candidate: CandidateDocument, *, verified_document_id: str,
        verified_at: str, verified_by: str, processed_path: str,
        verification_notes: str,
    ) -> "VerifiedDocument":
        if candidate.review_status != ReviewStatus.VERIFIED:
            raise ValueError("verified 상태의 candidate만 accepted 문서로 승격할 수 있습니다.")
        if candidate.source_tier == SourceTier.TIER_4:
            raise ValueError("Tier 4 discovery 자료는 verified corpus로 승격할 수 없습니다.")
        if candidate.total_quality_score < 75:
            raise ValueError("75점 미만 candidate는 verified corpus로 승격할 수 없습니다.")
        if candidate.rights_status not in {"public_domain", "open_license", "permission_granted"}:
            raise ValueError("RAG 이용이 명시적으로 허용된 권리 상태가 필요합니다.")
        if candidate.rights_evidence.human_review_required:
            raise ValueError("rights human review가 완료되지 않았습니다.")
        if candidate.rejection_reasons or candidate.duplicate_status == DuplicateStatus.CONFIRMED:
            raise ValueError("hard rejection 또는 확정 중복 candidate는 승격할 수 없습니다.")
        if not verified_by.strip() or not verification_notes.strip():
            raise ValueError("검수자와 검수 근거가 필요합니다.")
        return cls(
            candidate.candidate_id, verified_document_id, verified_at, verified_by,
            candidate.source_url, candidate.canonical_url, candidate.source_title,
            candidate.publisher, candidate.publisher_family, candidate.source_tier,
            list(candidate.topic_categories), candidate.historical_period,
            list(candidate.location), candidate.raw_path, candidate.raw_sha256,
            processed_path, candidate.rights_status, candidate.license,
            candidate.kogl_type, candidate.rights_evidence, dict(candidate.provenance),
            candidate.total_quality_score, candidate.fact_conflict,
            list(candidate.conflicting_values), verification_notes=verification_notes,
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
