"""Structured 100-point scoring with non-negotiable hard rejections."""

from __future__ import annotations

import re

from history_chatbot.history_collection.models import (
    AcceptanceStatus, CandidateDocument, DuplicateStatus, HardRejectionCode,
    ReviewStatus, SourceTier,
)
from history_chatbot.history_collection.quality import ContentQuality, HISTORY_TERMS, normalize_body
from history_chatbot.history_collection.rights import RightsDecision


SCORE_MAXIMA = {
    "authority_score": 20, "provenance_score": 15,
    "historical_relevance_score": 10, "mokpo_relevance_score": 10,
    "corroboration_score": 15, "content_quality_score": 10,
    "objectivity_score": 10, "rights_score": 10,
}


def _authority(candidate: CandidateDocument) -> int:
    return {SourceTier.TIER_1: 20, SourceTier.TIER_2: 16,
            SourceTier.TIER_3: 11, SourceTier.TIER_4: 3}[candidate.source_tier]


def _provenance(candidate: CandidateDocument) -> int:
    score = 0
    score += 4 if candidate.canonical_url else 0
    score += 4 if candidate.publisher and candidate.publisher_family else 0
    score += 4 if candidate.provenance.get("record_id") or candidate.provenance.get("publication_id") else 0
    score += 3 if candidate.provenance.get("discovered_from") or candidate.provenance.get("citation") else 0
    return min(score, 15)


def _objectivity(text: str, candidate: CandidateDocument) -> int:
    compact = normalize_body(text)
    sensational = len(re.findall(r"(?:충격|경악|반드시 믿|최고의|숨겨진 진실|!!!)", compact))
    attribution = len(re.findall(r"(?:에 따르면|기록|자료|보고서|연구|출처|소장)", compact))
    score = 6 + min(attribution, 4) - min(sensational * 3, 6)
    if candidate.provenance.get("author") or candidate.publisher:
        score += 1
    return max(0, min(score, 10))


def hard_rejections(candidate: CandidateDocument, quality: ContentQuality,
                    rights: RightsDecision) -> list[HardRejectionCode]:
    reasons = list(rights.hard_rejections)
    body = normalize_body(candidate.body_text)
    if not candidate.provenance or not candidate.canonical_url:
        reasons.append(HardRejectionCode.NO_PROVENANCE)
    if not candidate.publisher or not candidate.publisher_family:
        reasons.append(HardRejectionCode.NO_PUBLISHER)
    if "목포" not in (candidate.source_title + " " + body) and not candidate.location:
        reasons.append(HardRejectionCode.NOT_MOKPO_RELEVANT)
    if not any(term in body for term in HISTORY_TERMS) and not candidate.historical_period:
        reasons.append(HardRejectionCode.NO_HISTORICAL_BODY)
    if quality.title_only:
        reasons.append(HardRejectionCode.TITLE_ONLY)
    if quality.metadata_only and quality.body_length < 120:
        reasons.append(HardRejectionCode.NO_HISTORICAL_BODY)
    if candidate.document_type in {"search_result", "navigation"}:
        reasons.append(HardRejectionCode.SEARCH_RESULT_ONLY)
    if candidate.document_type in {"seo", "autogenerated"}:
        reasons.append(HardRejectionCode.SEO_AUTOGENERATED)
    if candidate.extraction_status != "success":
        reasons.append(HardRejectionCode.EXTRACTION_FAILED)
    if quality.ocr_corruption_ratio > 0.05 or quality.suspicious_repeated_characters:
        reasons.append(HardRejectionCode.OCR_CORRUPTION)
    if candidate.duplicate_status == DuplicateStatus.CONFIRMED:
        reasons.append(HardRejectionCode.DUPLICATE_MIRROR if candidate.duplicate_method == "mirror" else HardRejectionCode.DUPLICATE_EXACT)
    if candidate.source_tier == SourceTier.TIER_4:
        reasons.append(HardRejectionCode.TIER4_DISCOVERY_ONLY)
    return list(dict.fromkeys(reasons))


def score_candidate(candidate: CandidateDocument, quality: ContentQuality,
                    rights: RightsDecision, *, corroboration_score: int = 0) -> CandidateDocument:
    combined = normalize_body(candidate.source_title + " " + candidate.body_text)
    candidate.authority_score = _authority(candidate)
    candidate.provenance_score = _provenance(candidate)
    candidate.historical_relevance_score = min(10, 2 * sum(term in combined for term in HISTORY_TERMS))
    mokpo_hits = combined.count("목포") + sum(place in combined for place in candidate.location if place != "목포")
    candidate.mokpo_relevance_score = min(10, mokpo_hits * 3)
    candidate.corroboration_score = max(0, min(corroboration_score, 15))
    candidate.content_quality_score = quality.score
    candidate.objectivity_score = _objectivity(candidate.body_text, candidate)
    candidate.rights_score = rights.score
    candidate.total_quality_score = sum(getattr(candidate, name) for name in SCORE_MAXIMA)
    candidate.rejection_reasons = hard_rejections(candidate, quality, rights)
    candidate.review_status, candidate.acceptance_status = classify_score(
        candidate.total_quality_score, bool(candidate.rejection_reasons),
        rights.usable_for_rag, rights.needs_human_review,
    )
    return candidate


def classify_score(total: int, has_hard_rejection: bool, rights_usable: bool,
                   rights_needs_review: bool) -> tuple[ReviewStatus, AcceptanceStatus]:
    if has_hard_rejection:
        return ReviewStatus.AUTO_REJECTED, AcceptanceStatus.REJECTED
    if total >= 75 and rights_usable and not rights_needs_review:
        return ReviewStatus.AUTO_CANDIDATE, AcceptanceStatus.PENDING
    if total >= 60:
        return ReviewStatus.NEEDS_HUMAN_REVIEW, AcceptanceStatus.PENDING
    return ReviewStatus.AUTO_REJECTED, AcceptanceStatus.REJECTED
